// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhe_06Vre40iV4Na0ZpbAJ7ggEwax6tlY',
    appId: '1:601368050090:web:e330e06b5ecda2cf3b53d3',
    messagingSenderId: '601368050090',
    projectId: 'gymtracker-b14fb',
    authDomain: 'gymtracker-b14fb.firebaseapp.com',
    storageBucket: 'gymtracker-b14fb.firebasestorage.app',
    measurementId: 'G-ZJC3GNYN01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzuZgVkeRl5_26qQqi1dczXQ9xAo5SInA',
    appId: '1:601368050090:android:dafcf284955d1b1a3b53d3',
    messagingSenderId: '601368050090',
    projectId: 'gymtracker-b14fb',
    storageBucket: 'gymtracker-b14fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEN3aIoQZpVnqYtFPv89N5SQUk3RAtLc',
    appId: '1:601368050090:ios:9395a6995f6549993b53d3',
    messagingSenderId: '601368050090',
    projectId: 'gymtracker-b14fb',
    storageBucket: 'gymtracker-b14fb.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIEN3aIoQZpVnqYtFPv89N5SQUk3RAtLc',
    appId: '1:601368050090:ios:9395a6995f6549993b53d3',
    messagingSenderId: '601368050090',
    projectId: 'gymtracker-b14fb',
    storageBucket: 'gymtracker-b14fb.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhe_06Vre40iV4Na0ZpbAJ7ggEwax6tlY',
    appId: '1:601368050090:web:20a9f08c0adc4eba3b53d3',
    messagingSenderId: '601368050090',
    projectId: 'gymtracker-b14fb',
    authDomain: 'gymtracker-b14fb.firebaseapp.com',
    storageBucket: 'gymtracker-b14fb.firebasestorage.app',
    measurementId: 'G-M2VM11YDG2',
  );
}